##############################################################
# Document: https://gohugo.io/getting-started/configuration/ #
##############################################################

# The URL of the site
# Hostname (and path) to the root, e.g. https://bep.is/
baseURL = "/"

# The name of theme in `/themes/`.
theme = "bulma"

# Google Analytics tracking ID.
googleAnalytics = ""

# Disable Hugo generator meta tag in the HTML head.
disableHugoGeneratorInject =  true

# Default language to use.
defaultContentLanguage = "en"

# Render the default content language in subdir, e.g. /en/.
defaultContentLanguageInSubdir = false

# Set `true` for Chinese/Japanese/Korean languages.
hasCJKLanguage = false

# Workaround for https://github.com/gohugoio/hugo/issues/5687.
removePathAccents = true

# Enable Emoji emoticons support for page content.
enableEmoji = true

# The number of elements per page in pagination.
paginate = 25

# Listing summary length in words.
summaryLength = 70

[related]
    threshold = 80
    includeNewer = true
    toLower = true
    [[related.indices]]
        name = "tags"
        weight = 100
    [[related.indices]]
        name = "categories"
        weight = 80
     [[related.indices]]
        name = "date"
        weight = 10

[outputs]
    home = [ "HTML", "RSS", "JSON", "MANIFEST" ]
    section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.MANIFEST]
    mediaType = "application/manifest+json"
    rel = "manifest"
    notAlternative = true
