[fr]
    weight          = 1
    languageCode    = "fr"
    languageName    = "Français"

    # The copyright notice to display in the site footer.
    # To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
    copyright       = "&copy; {year} Wayne Ho"

    # The title of site
    title           = "Hugo-Bulma: Hugo theme based on Bulma"

    [fr.params]
        author = "Wayne Ho"
        keywords = "Hugo-Bulma, Hugo, Bulma, Theme"
        description = "Hugo-Bulma is a free, open source Hugo theme based on Bulma."

[en]
    weight          = 2
    languageCode    = "en"
    languageName    = "English"

    # The copyright notice to display in the site footer.
    # To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
    copyright       = "&copy; {year} Wayne Ho"

    # The title of site
    title           = "Hugo-Bulma: Hugo theme based on Bulma"

    [en.params]
        author = "Wayne Ho"
        keywords = "Hugo-Bulma, Hugo, Bulma, Theme"
        description = "Hugo-Bulma is a free, open source Hugo theme based on Bulma."